spring.application.name=maze_madness
#spring.web.resources.static-locations=classpath:/resources/
spring.web.resources.static-locations=file:///S:/FTP_Server/resources
#spring.thymeleaf.prefix=classpath:/resources/templates
spring.thymeleaf.prefix=file:///S:/FTP_Server/resources
spring.thymeleaf.suffix=.html
spring.thymeleaf.check-template-location=true
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false
spring.thymeleaf.servlet.content-type=text/html
server.port=8081
server.host=192.168.0.105
socket.port=8082

logging.level.root=info