socket:
  port: 8997
server:
#  host: ${SERVER_HOST}
  host: 192.168.0.105
  port: 8996
  error:
    include-message: always
    include-binding-errors: always
spring:
  application:
    name: MazeMadness
  config:
#    import: optional:file:.env[.properties]
    import: optional:classpath:.env[.properties]
  web:
    resources:
      static-locations: file:///S:/FTP_Server/resources
  thymeleaf:
    enabled: false
    check-template-location: true
    mode: HTML
    prefix: file:///S:/FTP_Server/resources
    suffix: .html
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html
  datasource:
    url: jdbc:postgresql://localhost:5432/registration
    username: ${SPRING_JDBC_USERNAME}
    password: ${SPRING_JDBC_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
jwt:
  secret: ${JWT_SECRET_KEY}
  lifetime: 1d
#cookie:
#  longLifetime: 7d
#  shortLifetime: 30m
#logging:
#  level:
#    root: info